apiVersion: v1
kind: Pod
metadata:
  name: votinig-app-pod
  labels:
    name: votinig-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: votinig-app-pod
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80



# kubectl create -f voting-app-pod.yaml
# kubectl create -f voting-app-service.yaml

# to check them both use: 
# kubectl get pods,svc 

# to print url use: 
# minikube service voting-app-service --url