apiVersion: v1 
kind: Service
metadata:
  name: votinig-app-service
  labels:
    name: votinig-app-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    name: votinig-app-pod
    app: demo-voting-app

